version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: school_app
    volumes:
      - .:/var/www/html
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: online_school
      DB_USERNAME: student
      DB_PASSWORD: password123
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: school_db
    environment:
      POSTGRES_DB: online_school
      POSTGRES_USER: student
      POSTGRES_PASSWORD: password123
    volumes:
      - ./docker/db_data:/var/lib/postgresql/data

  nginx:
    image: nginx:stable-alpine
    container_name: school_nginx
    ports:
      - "8081:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

